# -*- coding: utf-8 -*-
"""
Static curriculum data for the D'TALE Student Portal.
CHAPTERS mirrors the 42 chapters of the Notes page (dtale-study-notes.html).
Each chapter has exactly 10 keywords so the assignment generator's math
(50 assignments / 10 keywords = 5 clean rounds) works out evenly.
"""

CHAPTERS = [
    {"id": 1, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "AI, ML, Deep Learning & Generative AI", "kind": "concept",
     "keywords": ["artificial intelligence", "machine learning", "deep learning", "generative AI", "supervised learning", "unsupervised learning", "reinforcement learning", "neural network", "algorithm", "training vs inference"]},
    {"id": 2, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "History of AI \u2014 From Turing to ChatGPT", "kind": "concept",
     "keywords": ["Turing Test", "Dartmouth Conference", "AI Winter", "Expert Systems", "Deep Blue", "AlexNet", "Transformer architecture", "GPT-3", "ChatGPT", "AlphaGo"]},
    {"id": 3, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "All 8 AI Tools", "kind": "tool",
     "keywords": ["ChatGPT", "Gemini", "Claude", "Perplexity AI", "Hugging Face", "GitHub Copilot", "Grammarly", "AI presentation tools", "custom instructions", "AI Spaces"]},
    {"id": 4, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "Prompt Engineering \u2014 Basic to Advanced", "kind": "code",
     "keywords": ["role prompting", "few-shot prompting", "chain-of-thought", "RISEN framework", "system prompt", "prompt chaining", "meta-prompting", "prompt injection", "output formatting", "temperature"]},
    {"id": 5, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "Internet, Cloud & APIs", "kind": "code",
     "keywords": ["DNS", "IP address", "HTTP request", "REST API", "GET method", "POST method", "IaaS", "PaaS", "SaaS", "JSON response"]},
    {"id": 6, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "Python Basics \u2014 Files, Folders, APIs, JSON", "kind": "code",
     "keywords": ["variables", "for loop", "function", "file I/O", "json.dumps", "json.loads", "requests library", "dictionary", "f-string", "os.makedirs"]},
    {"id": 7, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "The PAA Project \u2014 End to End", "kind": "project",
     "keywords": ["4W framework", "PAA architecture", "Flask route", ".env file", "ai_engine.py", "task module", "router function", "CLI phase", "local web phase", "cloud deployment"]},
    {"id": 8, "part": "Phase 1 & 2 \u00b7 AI Foundation Thesis", "title": "RAG, Fine-Tuning, Agents & Ethics", "kind": "concept",
     "keywords": ["RAG", "vector database", "embeddings", "fine-tuning", "AI agent", "LangChain", "bias", "hallucination", "privacy", "intellectual property"]},
    {"id": 9, "part": "Phase 1 & 2 \u00b7 Supplements", "title": "AI Terminology & Data", "kind": "concept",
     "keywords": ["algorithm", "model", "training", "inference", "structured data", "unstructured data", "regression", "classification", "neural net layers", "data labelling"]},
    {"id": 10, "part": "Phase 1 & 2 \u00b7 Supplements", "title": "The AI Project Lifecycle", "kind": "concept",
     "keywords": ["problem definition", "data collection", "data cleaning", "model training", "evaluation", "deployment", "monitoring", "data scientist", "ML engineer", "domain expert"]},
    {"id": 11, "part": "Phase 1 & 2 \u00b7 Supplements", "title": "AI and Society", "kind": "concept",
     "keywords": ["bias", "privacy", "fairness", "transparency", "AI safety", "AI and jobs", "automation", "AI myths", "responsible AI", "human oversight"]},
    {"id": 12, "part": "Phase 1 & 2 \u00b7 Supplements", "title": "AI in Practice", "kind": "concept",
     "keywords": ["ML workflow", "NLP", "computer vision", "self-driving cars", "voice assistants", "recommendation systems", "human-AI collaboration", "sentiment analysis", "object detection", "translation"]},
    {"id": 13, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "What is Generative AI", "kind": "concept",
     "keywords": ["generative AI", "chatbot", "AI image generator", "AI writing tool", "AI coding assistant", "text generation", "image generation", "music generation", "video generation", "code generation"]},
    {"id": 14, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "What is an API", "kind": "concept",
     "keywords": ["API", "waiter analogy", "request", "response", "server", "client", "endpoint", "status code", "headers", "payload"]},
    {"id": 15, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Why Python + APIs", "kind": "concept",
     "keywords": ["Python", "weather API", "payment API", "database API", "social media API", "email API", "maps API", "AI model API", "requests library", "third-party service"]},
    {"id": 16, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Installing the Tools", "kind": "code",
     "keywords": ["pip install", "requests", "openai package", "google-generativeai", "python-dotenv", "virtual environment", "package manager", "pip upgrade", "requirements.txt", "import statement"]},
    {"id": 17, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Your First API Call", "kind": "code",
     "keywords": ["requests.get", "status code 200", "response.json()", "GitHub API", "base URL", "API response", "print statement", "error handling", "timeout", "connection error"]},
    {"id": 18, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "HTTP Methods", "kind": "code",
     "keywords": ["GET", "POST", "PUT", "DELETE", "idempotency", "request body", "query parameters", "HTTP status codes", "create vs update", "REST convention"]},
    {"id": 19, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "JSON, End to End", "kind": "code",
     "keywords": ["JSON syntax", "json.dumps", "json.loads", "json.dump", "json.load", "nested JSON", "JSON array", "key-value pair", "caching JSON", "JSON in NoSQL"]},
    {"id": 20, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "API Keys & .env", "kind": "code",
     "keywords": ["API key", ".env file", "load_dotenv", "os.getenv", ".gitignore", "secret key", "key rotation", "rate limiting", "environment variable", "key leak"]},
    {"id": 21, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "A Generative AI API", "kind": "code",
     "keywords": ["OpenAI client", "chat completion", "model parameter", "messages array", "system role", "user role", "assistant role", "max tokens", "temperature setting", "response parsing"]},
    {"id": 22, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Gemini API", "kind": "code",
     "keywords": ["genai.configure", "GenerativeModel", "generate_content", "Gemini API key", "model name", "prompt text", "response.text", "Google AI Studio", "multimodal input", "safety settings"]},
    {"id": 23, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Image Generation", "kind": "concept",
     "keywords": ["text-to-image prompt", "DALL-E", "Stable Diffusion", "Midjourney", "diffusion model", "image prompt engineering", "aspect ratio", "negative prompt", "style transfer", "upscaling"]},
    {"id": 24, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Weather, YouTube, Maps & Database APIs", "kind": "code",
     "keywords": ["weather API", "YouTube API", "Maps API", "sqlite3", "city parameter", "search query", "distance calculation", "database cursor", "API documentation", "free tier limits"]},
    {"id": 25, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Building an AI Assistant", "kind": "code",
     "keywords": ["system prompt", "conversation history", "while loop", "memory", "chat loop", "input function", "message list", "assistant role", "exit condition", "context window"]},
    {"id": 26, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Real Projects", "kind": "project",
     "keywords": ["AI chatbot", "resume analyzer", "AI teacher", "stock report generator", "PDF parsing", "feedback generation", "report formatting", "project scoping", "MVP", "user testing"]},
    {"id": 27, "part": "Phase 4, Part A \u00b7 GenAI & APIs", "title": "Safety Rules & Practice", "kind": "concept",
     "keywords": ["API key safety", ".gitignore", "rate limits", "secrets management", "practice plan", "daily habit", "deployment checklist", "security review", "least privilege", "key revocation"]},
    {"id": 28, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Frontend Development", "kind": "code",
     "keywords": ["HTML", "CSS", "JavaScript", "frontend", "DOM", "page reload problem", "single page app", "event handler", "responsive design", "browser rendering"]},
    {"id": 29, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "What is React.js", "kind": "code",
     "keywords": ["React component", "JSX", "LEGO analogy", "reusable component", "Button component", "Navbar component", "props", "render", "component tree", "Meta Platforms"]},
    {"id": 30, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "React Thinking", "kind": "concept",
     "keywords": ["UI as a function of data", "state", "re-render", "data change", "component update", "declarative UI", "one-way data flow", "virtual DOM", "state update", "UI consistency"]},
    {"id": 31, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "React and AI", "kind": "code",
     "keywords": ["chatbot UI", "message rendering", "chat box", "send button", "message list", "real-time update", "input state", "AI response display", "loading state", "scroll to bottom"]},
    {"id": 32, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "What is Backend", "kind": "concept",
     "keywords": ["backend", "ATM analogy", "login logic", "database", "security", "business logic", "server-side validation", "session", "authentication", "authorization"]},
    {"id": 33, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Node.js", "kind": "code",
     "keywords": ["Node.js", "Express", "app.get", "app.listen", "server port", "request handler", "res.send", "npm", "package.json", "middleware"]},
    {"id": 34, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "API Concept", "kind": "code",
     "keywords": ["API request flow", "React to Node", "Node server", "response cycle", "fetch call", "async request", "API contract", "error response", "loading indicator", "CORS"]},
    {"id": 35, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Building an API with Node", "kind": "code",
     "keywords": ["app.get route", "res.json", "route parameter", "students endpoint", "JSON response shape", "HTTP status", "route handler", "Express router", "API testing", "Postman"]},
    {"id": 36, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Database Connection", "kind": "code",
     "keywords": ["database table", "rows and columns", "SQL query", "round trip", "primary key", "foreign key", "database driver", "connection string", "query result", "ORM"]},
    {"id": 37, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Python + AI Connection", "kind": "code",
     "keywords": ["resume analyzer", "file upload", "AI scoring", "Node to Python handoff", "Python microservice", "score calculation", "feedback text", "multi-language stack", "internal API", "data passing"]},
    {"id": 38, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "FastAPI", "kind": "code",
     "keywords": ["FastAPI", "uvicorn", "@app.get decorator", "Python backend", "async endpoint", "automatic docs", "request validation", "Pydantic model", "port 8000", "JSON response"]},
    {"id": 39, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Complete AI App Architecture", "kind": "concept",
     "keywords": ["React layer", "Node layer", "Python layer", "AI model layer", "database layer", "full request cycle", "layer responsibility", "scaling a layer", "architecture diagram", "data flow"]},
    {"id": 40, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Real Project Example \u2014 AI Study Assistant", "kind": "project",
     "keywords": ["AI study assistant", "quiz generation", "note generation", "MongoDB", "feature list", "tech stack choice", "user flow", "MVP scope", "study question UI", "answer checking"]},
    {"id": 41, "part": "Phase 4, Part B \u00b7 Full-Stack Architecture", "title": "Full-Stack Skill Map", "kind": "concept",
     "keywords": ["beginner skills", "intermediate skills", "advanced skills", "HTML/CSS/JS", "React + Node", "AI APIs", "cloud deployment", "skill progression", "learning roadmap", "portfolio project"]},
    {"id": 42, "part": "Reference", "title": "Books, Papers & Career Roadmap", "kind": "concept",
     "keywords": ["AI for Everyone", "Attention Is All You Need", "Constitutional AI", "career roadmap", "AI consulting", "freelancing", "AI content creation", "AI research track", "agent development", "teaching AI"]},
]

PROJECTS = [
    {"id": 1, "title": "Personal AI Notebook", "tagline": "Your first end-to-end build.",
     "brief": "A command-line Python tool that takes any block of text (paste a paragraph, an email, or your own notes) and gives you back a summary, 3 key points, and one follow-up question \u2014 using a real AI API call.",
     "deliverables": ["Working CLI script", "At least 2 task types (summarize + Q&A)", "API key loaded safely from .env"],
     "stack": "Python, requests/openai, .env", "est_time": "1\u20132 days"},
    {"id": 2, "title": "Prompt Library Builder", "tagline": "Turn Phase 2 into a personal toolkit.",
     "brief": "Build a small web page (or Flask app) that stores your best prompts, lets you tag them by use-case, and lets you copy one with a click. This is the prompt library every PAA needs.",
     "deliverables": ["At least 15 saved prompts across 3 categories", "Search or filter by tag", "Copy-to-clipboard button"],
     "stack": "HTML/CSS/JS or Flask", "est_time": "2\u20133 days"},
    {"id": 3, "title": "No-Code AI Form", "tagline": "Phase 3, proven hands-on.",
     "brief": "Using any no-code platform (or plain HTML forms + Flask), build a feedback or signup form that saves submissions and uses an AI call to auto-categorize or summarize each entry.",
     "deliverables": ["A working form", "Submissions saved somewhere (file, sheet, or DB)", "One AI-generated field per submission"],
     "stack": "No-code tool, or Flask + SQLite", "est_time": "1\u20132 days"},
    {"id": 4, "title": "AI Resume Analyzer", "tagline": "The Phase 1 thesis capability, fully built.",
     "brief": "Upload a resume (PDF or text) and a job description; the AI scores the match and lists 3 concrete improvements. This is capability #34\u201340 from the PAA project, built standalone.",
     "deliverables": ["File upload working", "AI returns a score + 3 suggestions", "Clean output format"],
     "stack": "Python, Flask, PyPDF2/pdfplumber, AI API", "est_time": "2\u20133 days"},
    {"id": 5, "title": "Chat With Your Notes (Mini-RAG)", "tagline": "Phase 4's RAG chapter, made real.",
     "brief": "Take 5\u201310 of your own text notes, chunk them, embed them, and build a tiny Q&A tool that only answers using your notes as context \u2014 a working, minimal RAG pipeline.",
     "deliverables": ["Working chunk + embed step", "Retrieval step that finds relevant chunks", "Answers grounded in your own notes"],
     "stack": "Python, an embeddings API, a simple vector store (even a list + cosine similarity)", "est_time": "3\u20134 days"},
    {"id": 6, "title": "Personal AI Assistant (the PAA, deployed)", "tagline": "The flagship capstone from Chapter 7.",
     "brief": "Build the full PAA: a Flask web app with at least 10 of the 50 documented capabilities, organized into Text / Coding / Image / Research / Productivity. Deploy it so it's reachable from a phone.",
     "deliverables": ["At least 10 working capabilities", "A simple web UI with a task menu", "Deployed on Render, Railway, or similar"],
     "stack": "Python, Flask, OpenAI/Anthropic/Stability APIs", "est_time": "1 week"},
    {"id": 7, "title": "AI-Powered Weather + Maps Mini-App", "tagline": "Three APIs, one dashboard.",
     "brief": "A small dashboard that takes a city name, shows the current weather, the distance to one other city of your choice, and an AI-generated one-line packing tip based on the weather.",
     "deliverables": ["Weather API integrated", "Maps/distance API integrated", "One AI-generated text field combining both"],
     "stack": "Python or JS, 2 external APIs + 1 AI API", "est_time": "1\u20132 days"},
    {"id": 8, "title": "Full-Stack AI Chat App", "tagline": "Phase 4 Part B, all four layers, for real.",
     "brief": "Build the complete React + Node + Python + AI Model stack from Chapter 39 \u2014 a real chat interface where React handles the UI, Node manages routing, Python calls the AI model, and responses flow back up.",
     "deliverables": ["React frontend with a working chat UI", "Node API layer", "Python service calling an AI model", "End-to-end message flow working"],
     "stack": "React, Node/Express, Python (FastAPI or Flask), AI API", "est_time": "1\u20132 weeks"},
    {"id": 9, "title": "AI Study Assistant", "tagline": "Chapter 40's real project, built by you.",
     "brief": "An app where a student pastes their study material and gets back auto-generated notes and a 5-question quiz, with answer checking.",
     "deliverables": ["Notes generation from raw text", "Auto-generated quiz (5+ questions)", "Answer checking with feedback"],
     "stack": "Your choice \u2014 Flask/FastAPI + AI API + any frontend", "est_time": "3\u20135 days"},
    {"id": 10, "title": "Capstone: Your Own AI Product", "tagline": "Everything you've learned, aimed at a real problem.",
     "brief": "Pick a real problem from your own life, studies, or community. Design it with the 4W framework from Chapter 7, build it across at least 3 of the layers covered in this curriculum, and deploy it somewhere reachable by a real user who isn't you.",
     "deliverables": ["A written 4W problem analysis", "A working, deployed product", "One real person outside yourself who has used it and given feedback"],
     "stack": "Your choice \u2014 this is the one where you decide", "est_time": "2+ weeks"},
]
